# Generated by Django 4.2.11 on 2024-03-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('pokemon', 'Pokemon'), ('trainer', 'Trainer'), ('energy', 'Energy')], max_length=10)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('pokemon_type', models.CharField(blank=True, max_length=50, null=True)),
                ('attacks', models.TextField(blank=True, null=True)),
                ('effects', models.TextField(blank=True, null=True)),
                ('attack_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('weakness', models.CharField(blank=True, max_length=50, null=True)),
                ('resistance', models.CharField(blank=True, max_length=50, null=True)),
                ('retreat_cost', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, choices=[('basic', 'Basic'), ('stage1', 'Stage 1'), ('stage2', 'Stage 2')], max_length=10, null=True)),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pkmn_tcg.pokemoncard')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkmn_tcg.deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='pkmn_tcg.pokemoncard'),
        ),
    ]
