# Generated by Django 4.2.11 on 2024-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmn_tcg', '0002_alter_pokemoncard_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemoncard',
            old_name='attacks',
            new_name='attack_1_effect',
        ),
        migrations.RenameField(
            model_name='pokemoncard',
            old_name='effects',
            new_name='attack_2_effect',
        ),
        migrations.RemoveField(
            model_name='pokemoncard',
            name='attack_cost',
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack_1_cost',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack_1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack_2_cost',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
