# Generated by Django 4.2.11 on 2024-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmn_tcg', '0003_rename_attacks_pokemoncard_attack_1_effect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemoncard',
            old_name='attack_1_effect',
            new_name='ability',
        ),
        migrations.RemoveField(
            model_name='pokemoncard',
            name='attack_2_effect',
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack_1_effects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='attack_2_effects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('burned', 'Burned'), ('poisoned', 'Poisoned'), ('asleep', 'Asleep'), ('confused', 'Confused'), ('paralyzed', 'Paralyzed')], default='normal', max_length=10),
        ),
    ]
